{% set name = "setproctitle" %}
{% set version = "1.3.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9f32b96c700bb384f33f7cf07954bb609d35dd82752cef57fb2ee0968409169

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - setproctitle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dvarrazzo/py-setproctitle
  license: BSD-3-Clause
  license_file: COPYRIGHT
  license_family: BSD
  summary: A library to allow customization of the process title.
  description: |
    The setproctitle module allows a process to change its title
    (as displayed by system tools such as ps, top or MacOS Activity 
    Monitor).
    
    Changing the title is mostly useful in multi-process systems, for
    example when a master process is forked: changing the children's
    title allows to identify the task each process is busy with. The
    technique is used by PostgreSQL and the OpenSSH Server for example.
  dev_url: https://github.com/dvarrazzo/py-setproctitle
  doc_url: https://github.com/dvarrazzo/py-setproctitle

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
