{% set name = "setproctitle" %}
{% set version = "1.3.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9f32b96c700bb384f33f7cf07954bb609d35dd82752cef57fb2ee0968409169
  patches:
  # Few tests compile C code at runtime by invoking 'cc', make them use Conda toolchain instead.
  #  - patches/0000_use_conda_cc_in_tests.patch
    - patches/test_patch.patch

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - setproctitle
  requires:
    - python
    - pip
    - pytest
    # Tests [test_embedded, test_embedded_many_args] compile C code at test runtime by invoking C compiler
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://github.com/dvarrazzo/py-setproctitle
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: A library to allow customization of the process title.
  description: |
    The setproctitle module allows a process to change its title
    (as displayed by system tools such as ps, top or MacOS Activity 
    Monitor).
    
    Changing the title is mostly useful in multi-process systems, for
    example when a master process is forked: changing the children's
    title allows to identify the task each process is busy with. The
    technique is used by PostgreSQL and the OpenSSH Server for example.
  dev_url: https://github.com/dvarrazzo/py-setproctitle
  doc_url: https://github.com/dvarrazzo/py-setproctitle

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
