{% set version = "1.1.10" %}

package:
    name: setproctitle
    version: {{ version }}

source:
    fn: setproctitle-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/s/setproctitle/setproctitle-{{ version }}.tar.gz
    md5: 2dcdd1b761700a5a13252fea3dfd1977

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - setproctitle

about:
    home: http://code.google.com/p/py-setproctitle/
    license: BSD 3-clause
    license_family: BSD
    summary: 'A library to allow customization of the process title.'

extra:
    recipe-maintainers:
        - pelson
        - ocefpaf
        - scopatz
