travis:
  secure:
    BINSTAR_TOKEN: L/b6EF1oBrDg2+XD7iKhdf8U4GPdOBJMgNsXL8Knz3UPU5sCCpb9E5brYxT7UIFRhuydNTK7wLeinC7NOA9II/hm2prfHdpmavWvnjrsCO2LZhPZLlcrZhoxcp5WsqTTaIGznKtkklljQcA5oBOJPxkQeNeCEBsqjpx0OLnaUPIKIrOH7KMzYRZ3q3u6RaGltmqhQrIXAbYYkr0EzZhzLXKNu7suEC3QNoZ55LMkxu0OXwhiOlwT/39aaVdjjwfgZheQwX6isvUrEuPZYj7pGD/a9ABHLoN8aVBUXuxnzPcoLUgV6wj8J+DDwJDN8sCaenu037EQGQDEAw+QLukBBINN5H5mDgMZzmM1Es8+BNryBRkqOld7yc5Sv3IHtsPRcyagOQQEXsjApB0GCURjP4/BaRQ1MZIJyVHMxxYfOdi55tNOA9guG/SFAHYxbL4FGOXg/TKx/jceFKUd75cstmLQUL55mfoltZ8Sln7epD8l/QV3/0u3zC5oCqhjKQbAmcN3z7hiH+d2C+nWpPh4cdQb2vbEhAtK31wvl6GRa8iZrMTFn6QgGiJxD/cql20Kk9Uys/9hQ7fPwBIu8nF58lv9JdQy4kEzu2ofh9nTd/atDE3bRLTzXUZOAIR3p2Uwtlc35TBUiu9cugQAPB9Oqh+xyTU/3EwItXC3C0ChINc=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
