travis:
  secure:
    BINSTAR_TOKEN: 2y2v/1vLBVEwVKe6WdQl2pGwllkJ6DZsClidwHW/DFl4bDbBhFM0OQGjzfo7Fcqj5g/Vc1OhRamnkdP2yE1v4Vyw4zvbJE1aam6SPWdCAAIH6r8SLQtUVSZqY4xLAFyOJVCYqja7ZsefLv1xmQcl+ZN7F4gcUGBTL+1J9u8ZKsKIx9u1rw6azwTuIM0eqOY+7rR2Gpf96HqvrNBwbAlxV+0hiq1y8R8MqnWYH2fs8Kaj2nQqJvoH0VfDLsE1vg0tbAj/hE99EusiiAeD460iMgLkBm64Tgc69uYbJwJRwZQDCmNc6bl9WYD6DVEUBzHPQVUOuGGXiGp50a0erLqZV+X3zZRhm9Oobj/o4Q1gXXG92cOcqvr7lAacFuWO5wds3E9TOVNitnYuctNjZWT9kO3Wht+82aqJ365ItkUipaMdy7pSOqatNTM2bipSBjJqu3yIzQF+ah4r1m6l2irBoi7b6c6fl5qiJ8HLIPgRluTq7zfaYizzzOtLK5IEVYi9EtB6JlIgkeE2lGUQa8juEjndEJjH1aq/aHyzZEAYjCjWyrGHZ/1AW4AQd9eNNeth6HUpvP+puuapZD8yVp4KObHM6JfapzEGAboTrePTZssinoCviUATJhNQHiH2iQUTF3E4EL+Brww1Z5CZz5NkffDQCVWdnUa8RcRfVAZVLTs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
